name: ITAS276-Assignment 1 Part 1 (All Remote)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Discord Webhook Action (Start Docker Build)
        uses: tsickert/discord-webhook@v7.0.0
        with: 
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: ${{github.repository}}
          avatar-url: https://robohash.org/itas
          embed-title: "🐋 Buidling Docker Image & Starting Pipeline"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "Building ${{ vars.DOCKER_IMAGE }}:latest\n[View Pipeline](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
          embed-author-url: "https://github.com/${{ github.triggering_actor }}"
          embed-color: 3447003
  
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_IMAGE }}:latest

      - name: Discord Webhook Action (Finish Docker Build)
        uses: tsickert/discord-webhook@v7.0.0
        with: 
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: ${{github.repository}}
          avatar-url: https://robohash.org/itas
          embed-title: "🐳 Docker Build Complete"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "Built ${{ vars.DOCKER_IMAGE }}:latest\n[View on Docker Hub](https://hub.docker.com/repository/docker/${{ vars.DOCKER_IMAGE }})"
          embed-author-name: "${{ github.triggering_actor }}"
          embed-author-url: "https://github.com/${{ github.triggering_actor }}"
          embed-color: 3447003

  semgrep:
    name: Semgrep (SAST)
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    
    outputs:
      semgrep-serif-url: ${{ steps.semgrep-serif-upload.outputs.artifact-url }}

    steps:
      - name: Discord Webhook Action (Start Semgrep (SAST))
        uses: tsickert/discord-webhook@v7.0.0
        with: 
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: ${{github.repository}}
          avatar-url: https://robohash.org/itas
          embed-title: "🕵️ Starting Semgrep (SAST) Analysis"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[View Pipeline](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          embed-author-name: "${{ github.triggering_actor }}"
          embed-author-url: "https://github.com/${{ github.triggering_actor }}"
          embed-color: 5763719

      - name: Checkout
        uses: actions/checkout@v4

      - name: Semgrep Scan 
        run: semgrep scan --sarif --sarif-output=semgrep.sarif
        #https://semgrep.dev/docs/getting-started/cli-oss
    
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4 
        with:
          id: semgrep-sarif-upload
          name: semgrep.sarif
          path: semgrep.sarif

      - name: Discord Webhook Action (Start Semgrep (SAST))
        uses: tsickert/discord-webhook@v7.0.0
        with: 
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: ${{github.repository}}
          avatar-url: https://robohash.org/itas
          embed-title: "✔️ Finished Semgrep (SAST) Analysis"
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-description: "[Download semgrep.sarif](${{ needs.semgrep.outputs.semgrep-serif-url }}"
          embed-author-name: "${{ github.triggering_actor }}"
          embed-author-url: "https://github.com/${{ github.triggering_actor }}"
          embed-color: 5763719    
          

  snyk:
    name: Snyk (SCA)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Pull
        run: docker pull ${{ vars.DOCKER_IMAGE }}:latest

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SYNK_API_KEY }}
        with:
          image: ${{ vars.DOCKER_IMAGE }}:latest
          args: --file=Dockerfile

      - name: Upload Artifact 
        uses: actions/upload-artifact@v4 
        with:
          name: snyk.sarif
          path: snyk.sarif