name: ITAS276-Assignment 1 Part 1 (All Remote)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_IMAGE }}:latest
  
  semgrep:
    name: Semgrep (SAST)
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semgrep Scan 
        run: semgrep scan --sarif --sarif-output=semgrep.sarif
        #https://semgrep.dev/docs/getting-started/cli-oss
    
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4 
        with:
          name: semgrep.sarif
          path: semgrep.sarif

  snyk:
    name: Snyk (SCA)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Pull
        run: docker pull ${{ vars.DOCKER_IMAGE }}:latest

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SYNK_API_KEY }}
        with:
          image: ${{ vars.DOCKER_IMAGE }}:latest
          args: --file=Dockerfile

      - name: Upload Artifact 
        uses: actions/upload-artifact@v4 
        with:
          name: snyk.sarif
          path: snyk.sarif